id: b83af4d39108481895b2087bb85940c0
initial_creation_type: ocr
source_metadata:
  volumes:
    229fe35d4829466694dc0e2036dd5c28:
      base_file: v018.txt
      image_group_id: I1PD95863
      title: ''
      total_pages: 1634
      volume_number: 18
